=== yeyanbo/art-decor/decor/core/DECOR-i18n.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
    
    DECOR internationalization i18n schema
    Copyright (C) 2009-2014 Dr. Kai U. Heitmann
    
    This program is free software; you can redistribute it and/or modify it under the terms 
    of the GNU General Public License as published by the Free Software Foundation; 
    either version 3 of the License, or (at your option) any later version.
    
    This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
    without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
    See the GNU General Public License for more details.
    
    See http://www.gnu.org/licenses/gpl.html
    
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    
    <!-- include DECOR datatype defintions -->
    <xs:include schemaLocation="DECOR-datatypes.xsd"/>
    
    <xs:element name="messsages">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="entry" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="text" minOccurs="1" maxOccurs="unbounded"/>
                        </xs:sequence>
                        <xs:attribute name="key" type="xs:string" use="required">
                            <xs:annotation>
                                <xs:documentation xml:lang="en-US">A key string as an index</xs:documentation>
                            </xs:annotation>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="uniqueKey">
            <xs:selector xpath="entry"/>
            <xs:field xpath="@key"/>
        </xs:unique>
    </xs:element>
    
    <xs:element name="text">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:any minOccurs="0" maxOccurs="unbounded" namespace="##any" processContents="skip"/>
            </xs:sequence>
            <xs:attribute name="language" type="LanguageCode" use="required"/>
        </xs:complexType>
    </xs:element>
    
</xs:schema>

=== yeyanbo/art-decor/decor/core/DECOR-i18n.xml
<messsages xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:sch="http://www.ascc.net/xml/schematron" xsi:noNamespaceSchemaLocation="DECOR-i18n.xsd">

    <!--  parameters in entry text denoted as %%1, %%2 etc. -->

    <!-- ==== general entries ====
         =========================
    -->
    <entry key="disclaimer">
        <text language="en-US">The content of this publication has been carefully prepared and reviewed. However, %%1 does not guarantee the accuracy, completeness or quality of the information
            provided, or that it is up-to-date. Liability claims against %%1 in respect of material or immaterial damage caused by the use or non-use of the information offered or by inaccurate or
            incomplete information are in principle ruled out provided that there is no provable culpable intent or gross negligence on the institute’s part.</text>
        <!--<text language="nl-NL">Hoewel deze publicatie met de uiterste zorg is samengesteld, kan %%1 geen aansprakelijkheid aanvaarden voor directe of indirecte schade ontstaan door de inhoud van de – al
            dan niet door derden aangeboden – informatie.</text>-->
        <text language="nl-NL">De inhoud van deze publicatie is zorgvuldig voorbereid en beoordeeld. Echter staat %%1 noch in voor de juistheid, volledigheid of kwaliteit van de verstrekte informatie 
            noch dat het up-to-date is. Aansprakelijkheid claims tegen %%1 ten aanzien van materiële of immateriële schade veroorzaakt door het gebruik of het niet-gebruik van de aangeboden 
            informatie of door onjuiste of onvolledige informatie zijn in principe uitgesloten op voorwaarde dat er geen aantoonbare toerekenbare opzet of grove schuld van de kant van het instituut.</text>
        <text language="de-DE">Der Inhalt dieser Publikation wurde sorgfältig bearbeitet und überprüft. Allerdings garantiert %%1 weder die Richtigkeit, Vollständigkeit oder Qualität der
            bereitgestellten Informationen, noch dass sie auf dem neuesten Stand sind. Haftungsansprüche gegen %%1 in Bezug auf Schäden materieller oder ideeller Art, 
            die durch die Nutzung oder Nichtnutzung der dargebotenen Informationen oder durch fehlerhafte und unvollständige Informationen verursacht wurden,
            sind grundsätzlich ausgeschlossen, sofern kein nachweislich vorsätzliches oder grob fahrlässiges Verschulden von %%1 vorliegt.</text>
    </entry>

    <!-- assert and report error examples
        ================================
        %%1 is always the item label
        
        * The value for “ClinicalDocument/code” SHALL be selected from ValueSet 1.2.34.1.25 LoincDocumentTypeCode DYNAMIC.
        Or
        * The value for “ClinicalDocument/code” SHOULD be selected from ValueSet 1.2.34.1.25 LoincDocumentTypeCode OR ValueSet 1.2.34.1.26 SnomedCtDocumentTypeCode DYNAMIC.
        Or
        * The value for “ClinicalDocument/code” SHOULD be selected from ValueSet 1.2.34.1.25 LoincDocumentTypeCode DYNAMIC.
        Or
        * The value for “ClinicalDocument/code” SHALL be selected from ValueSet 1.2.34.1.25 DYNAMIC.
        Or
        * The value for “ClinicalDocument/code” SHOULD be selected from ValueSet LoincDocumentTypeCode DYNAMIC.
        
        
        * The value for “ClinicalDocument/code” SHALL be selected from ValueSet 1.2.34.1.25 LoincDocumentTypeCode STATIC 20061017.
        Or
        * The value for “ClinicalDocument/code” SHALL be selected from ValueSet 1.2.34.1.25 LoincDocumentTypeCode OR ValueSet 1.2.34.1.26 SnomedCtDocumentTypeCode STATIC 20061017.
        Or
        * The value for “ClinicalDocument/code” SHOULD be selected from ValueSet 1.2.34.1.25 LoincDocumentTypeCode STATIC 20061017.
        Or
        * The value for “ClinicalDocument/code” SHALL be selected from ValueSet 1.2.34.1.25 STATIC 20061017.
        Or
        * The value for “ClinicalDocument/code” SHOULD be selected from ValueSet LoincDocumentTypeCode STATIC 20061017.
        
        
        * The value for “ClinicalDocument/code” SHALL be 42134-7 “DischargeSummary” 2.16.840.1.113883.6.1 LOINC STATIC 20061017.
        

    -->

    <!-- ==== PART A: schematron messages ====
         =====================================
    -->
    <entry key="attribCodeset">
        <!-- 1:item / 2:element / 3:set of codes -->
        <text language="en-US">%%1: The value for %%2 SHALL be selected from the following codes: %%3.</text>
        <text language="de-DE">%%1: Der Wert von %%2 MUSS einer der folgenden Kodes enthalten: %%3.</text>
        <text language="nl-NL">%%1: de waarde van %%2 MOET één van de volgende codes bevatten: %%3.</text>
    </entry>
    <entry key="attribCode">
        <!-- 1:item / 2:element / 3:value set name and or id / 4:stability -->
        <text language="en-US">%%1: The value for %%2 SHALL be selected from value set %%3. NOTE: codeSystemVersion SHALL match exactly if specified in the value set.</text>
        <text language="de-DE">%%1: Der Wert von %%2 MUSS gewählt werden aus dem Value Set %%3. NOTE: codeSystemVersion SHALL match exactly if specified in the value set.</text>
        <text language="nl-NL">%%1: de waarde van %%2 MOET worden gekozen uit waardelijst %%3. NB: codeSystemVersion MOET exact overeenkomen indien gespecificeerd in de waardelijst.</text>
    </entry>
    <entry key="attribCodeCS">
        <!-- 1:item / 2:element / 3:value set name and or id / 4:stability -->
        <text language="en-US">%%1: The value for %%2 SHALL be selected from %%3.</text>
        <text language="de-DE">%%1: Der Wert von %%2 MUSS gewählt werden aus %%3.</text>
        <text language="nl-NL">%%1: de waarde van %%2 MOET worden gekozen uit %%3.</text>
    </entry>
    <entry key="validNullCode">
        <!-- 1:item / 2:element / 3:value set name and or id / 4:stability -->
        <text language="en-US">%%1: The null value '<value-of xmlns="http://purl.oclc.org/dsdl/schematron" select="@nullFlavor"/>' for %%2 SHALL be selected from the set of valid null flavors defined for this attribute or those associated with Value Set %%3.</text>
        <text language="de-DE">%%1: Der fehlende Wert '<value-of xmlns="http://purl.oclc.org/dsdl/schematron" select="@nullFlavor"/>' für %%2 MUSS gewählt werden aus dem Set gültiger null flavors für dieses Attribut oder denen assoziiert mit Value Set %%3.</text>
        <text language="nl-NL">%%1: de nulwaarde '<value-of xmlns="http://purl.oclc.org/dsdl/schematron" select="@nullFlavor"/>' voor %%2 MOET komen uit de set die is gedefinieerd voor dit attribuut of zijn gekoppeld aan waardelijst %%3.</text>
    </entry>
    <entry key="attribValue">
        <!-- 1:item / 2:element / 3:value of the element -->
        <text language="en-US">%%1: The value for %%2 SHALL be '%%3'.</text>
        <text language="de-DE">%%1: Der Wert von %%2 MUSS '%%3' sein.</text>
        <text language="nl-NL">%%1: de waarde van %%2 MOET '%%3' zijn.</text>
    </entry>
     <entry key="attribValue2">
        <!-- 1:item / 2:value of the element -->
        <text language="en-US">%%1: The element value SHALL be %%2.</text>
        <text language="de-DE">%%1: Der Elementinhalt MUSS sein %%2.</text>
        <text language="nl-NL">%%1: de elementwaarde MOET zijn %%2.</text>
    </entry>
    <entry key="attribElmContent">
        <!-- 1:item / 2:element / 3:value of the element content-->
        <text language="en-US">%%1: the element content of %%2 SHALL be '%%3'.</text>
        <text language="de-DE">%%1: Der Elementinhalt von '%%2' MUSS '%%3' sein.</text>
        <text language="nl-NL">%%1: de element content van %%2 MOET '%%3' zijn.</text>
    </entry>
    <entry key="attribPresent">
        <text language="en-US">%%1: attribute @%%2 SHALL be present.</text>
        <text language="de-DE">%%1: Attribut @%%2 MUSS vorkommen.</text>
        <text language="nl-NL">%%1: attribute @%%2 MOET aanwezig zijn.</text>
    </entry>
    <entry key="attribProhibited">
        <text language="en-US">%%1: attribute @%%2 MAY NOT be present.</text>
        <text language="de-DE">%%1: Attribut @%%2 DARF NICHT vorkommen.</text>
        <text language="nl-NL">%%1: attribute @%%2 MAG NIET voorkomen.</text>
    </entry>
    <entry key="attribTimeStampPrec">
        <text language="en-US">%%1: %%2 SHALL be a valid time stamp and of precision/format '%%3'.</text>
        <text language="de-DE">%%1: %%2 MUSS eine gültige Zeitangabe mit der Genauigkeit/Format '%%3' sein.</text>
        <text language="nl-NL">%%1: %%2 MOET een geldig tijdstip met precisie/formaat '%%3' zijn.</text>
    </entry>
    <entry key="attribTimeStamp">
        <text language="en-US">%%1: %%2 SHALL be a valid time stamp, invalid '%%3'.</text>
        <text language="de-DE">%%1: %%2 MUSS ein gültige Zeitangabe sein, ungültig '%%3'.</text>
        <text language="nl-NL">%%1: %%2 MOET een geldig tijdstip, ongeldig '%%3'.</text>
    </entry>
    <entry key="rootUuidOrOid">
        <text language="en-US">%%1: @root attribute SHALL be a syntactically correct UUID or OID.</text>
        <text language="de-DE">%%1: @root Attribut MUSS eine syntaktisch korrekte UUID oder OID sein.</text>
        <text language="nl-NL">%%1: @root attribuut MOET een syntactisch correcte UUID of OID zijn.</text>
    </entry>
    <entry key="elmWithRootPresent">
        <text language="en-US">%%1: at least one %%2 element SHALL be present where the value of @root is '%%3' only.</text>
        <text language="de-DE">%%1: es MUSS mindestens ein %%2 Element anwesend sein wobei der Wert von @root '%%3' ist.</text>
        <text language="nl-NL">%%1: minstens één %%2 element MOET aanwezig zijn met de waarde '%%3' in @root.</text>
    </entry>
    <entry key="rootValue">
        <text language="en-US">%%1: @root SHALL have value '%%2'.</text>
        <text language="de-DE">%%1: @root MUSS den Wert '%%2' haben.</text>
        <text language="nl-NL">%%1: @root MOET de waarde '%%2' hebben.</text>
    </entry>
    <entry key="elmProhibited">
